### ISSUE TITLE
Make Test failed

### ISSUE THREAD

**Issue by smehta** [facebook/SocketRocket#19]
Hi Mike, 

I am trying to run SocketRocket but tests are failing.

command: make test
Error as follows:

*\* BUILD FAILED **

The following build commands failed:
    PhaseScriptExecution "Run Script" build/SocketRocket.build/Debug-iphonesimulator/SRWebSocketTests.build/Script-F6BDA800145900D200FE3253.sh
(1 failure)
./TestSupport/run_test.sh: line 23: kill: (16474) - No such process
make: **\* [test_all] Error 1

Thanks,
Sahil

**Comment by bhaveshtandel** [comment]
** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution Run\ Script /Users/dakshpasbola/Library/Developer/Xcode/DerivedData/SocketRocket-dawiprgjuvsviafrwfumgixoises/Build/Intermediates/SocketRocket.build/Debug-iphonesimulator/SRWebSocketTests.build/Script-F6BDA800145900D200FE3253.sh
(1 failure)
./TestSupport/run_test.sh: line 26: kill: (5581) - No such process
The file /Users/dakshpasbola/Desktop/SocketRocket/pages/results/index.html does not exist.
make: *** [test] Error 1
