### ISSUE TITLE
No error when trying to send through non-opened socket

### ISSUE THREAD

**Issue by mahsuscuktan** [facebook/SocketRocket#206]
I have a class which conforms to SRWebSocketDelegate and has an SRWebSocket property. The socket opens when user opens a screen. Then messages are sent to an echo server through that socket. I have successfully tested this scenario with a prototype project. When I tried the same in actual project, I realized that the socket never gets opened. I have put an NSLog and a breakpoint in webSocketDidOpen: method only to find out that it does not get called. I am using SocketRocket as a framework; though I do not think this is the issue as the prototype project runs smoothly "in the same boat". I thought the issue might be related to AFNetworking, so I have put the pod and related codes in the prototype project yet it still runs as expected. In fact I have almost moved entire project to the prototype; yet it did not break. I am asking how to debug this "issue" as I run out of options but to drop SocketRocket from project.

P.S: I have also realized that even the socket is not open (SRWebSocket's readyState is SR_CLOSED) the message is sent (I mean there is no error whatsoever). The code gets passed this line
NSAssert(self.readyState != SR_CONNECTING, @"Invalid State: Cannot call send: until connection is open");
 even when ready state is not SR_CONNECTING.

**Comment by paultnp** [comment]
I have the same issue. Can this be resolved.
