### ISSUE TITLE
Document ping/pong

### ISSUE THREAD

**Issue by mattdipasquale** [facebook/SocketRocket#209]
Please document the new ping & pong methods.

They're missing from the README.md file.

Also, when/why should we use these?

How do you use these?

Do you need to configure your server somehow to work with these?

What does a ping and a pong message look like?

Please explain in detail. Thanks!

**Comment by danielribeiro** [comment]
Sounds like a reasonable request.

**Comment by galambalazs** [comment]
Ping-pong

**Use-case 1**: keeping the connection alive (sending something small even if there are no other messages to send) 

Example: Amazon Elastic Load Balancer terminates connections after 60 seconds of inactivity by default. 

Ping is basically just a header stating the message type and an optional payload, e.g. a ' ' space character.
Pong is then a header stating that it's a pong message type and the same data that the Ping had.


**Use-case 2**: ensuring the server/client is still alive

If I say Ping and you don't respond with a Pong then I can consider our connection dead.

E.g. your iphone loses network, it cannot send anything to the server to let it know your connection is dead, so without some kind of ping-pong you won't notice the dead connection.

**What you need to do**

If you use a decent socket library on the server it should *automatically* respond to Ping messages with a *Pong answer*. Socket Rocket automatically responds to Ping messages with *Pong answers*.

But *you need to decide* where you want to send Ping messages from: server/client

Then you need to implement sending Ping messages with a timer.:

```
init()
  - start ping timer (e.g. 30 seconds)

didReceiveMessage
  - delay ping timer 30 seconds (because the connection was active)

didSendMessage
  - delay ping timer 30 seconds (because the connection was active)

onPingTimer
  - send ping message (if you reach this method, there were no messages for 30 seconds)
```

Again this can go to either the client or server side.

**Comment by nlutsenko** [comment]
@galambalazs, that's a perfect answer!
I believe this answers the question fully.
SocketRocket will always respond with `pong` message when the server sends a `ping`, so no action is required.

For manual `ping` - you can implement optional delegate method to handle the server `pong` reply to be informed whether the connection to the server is alive or not.
