### ISSUE TITLE
Empty loop consumes CPU on an otherwise idle app.

### ISSUE THREAD

**Issue by sgourichon** [facebook/SocketRocket#229]
Observed on a project running on iOS 8.
SocketRocket is used by some versions of SocketIO that we use. 
We observed an empty loop consuming CPU even when application is idle.
Expected behavior is that idle application does not consume CPU.
The line containing the empty loop still exists on current master, see https://github.com/square/SocketRocket/blob/a2dd92a13b42e14fee0c93253e464121c1de67d5/SocketRocket/SRWebSocket.m#L1756
Regards.

**Comment by mikelikespie** [comment]
So

`[_runLoop runMode:NSDefaultRunLoopMode beforeDate:[NSDate distantFuture]]` 

should block until there's an event to be run on the runloop. It should not be spinning. Although they may have changed.

**Comment by nlutsenko** [comment]
Looks like this was changed #247 and shipped in the latest release.
@sgourichon, please reopen/comment if you run into performance issues with the latest version.
