### ISSUE TITLE
Performance issue iOS 8.3

### ISSUE THREAD

**Issue by jochenschoellig** [facebook/SocketRocket#236]
Hello,

I experience performance issues in my app since iOS 8.3. If I run the exact same app on two iPhone 6 one with iOS 8.2 and one with iOS 8.3 there are visible delays. The time since a message is displayed on the app is more then doubled on iOS 8.3.

Debugging showed that the delay comes from SocketRocket and doesn't happen in my code.

Does anybody experience the same issues?
Could it be possible that Apple changed something in CFStream?

Thank you!

**Comment by mikelikespie** [comment]
This may be related to https://github.com/square/SocketRocket/issues/229

**Comment by nlutsenko** [comment]
Looks like #229 was a report about the same issue and this was changed #247 and shipped in the latest release. Please reopen/comment if you run into any performance issues.
