### ISSUE TITLE
SocketRocket does not support the Sec-WebSocket-Protocol header

### ISSUE THREAD

**Issue by matzew** [facebook/SocketRocket#24]
The SocketRocket library does not support the Sec-WebSocket-Protocol header:

From the spec:
....
Sec-WebSocket-Protocol: chat, superchat
....

http://tools.ietf.org/html/rfc6455#section-1.2

Suggested API would be something like:
- (id)initWithURLRequest:(NSURLRequest _)request subprotocol:(NSString_)subprotocol;

**Comment by sashakid** [comment]
Hi, is that all about error `Error Domain=SRWebSocketErrorDomain Code=2133 "Invalid Sec-WebSocket-Accept response." UserInfo={NSLocalizedDescription=Invalid Sec-WebSocket-Accept response.}`?
