### ISSUE TITLE
How to identify a websocket silently closing

### ISSUE THREAD

**Issue by dickensas** [facebook/SocketRocket#260]
The Websocket is closed by the server, but none of the callback functions triggered, Is there anywhere I can put a break point and see where it is going when a socket is closed?

**Comment by bithavoc** [comment]
Added more details here https://github.com/square/SocketRocket/issues/266

**Comment by lvandyk** [comment]
Has this been pulled? I am experiencing this issue.

**Comment by lvandyk** [comment]
Anyone?

**Comment by kommen** [comment]
@lvandyk I think we had the same issue. Does sound #268 like your problem? That was fixed with version 0.4.2 though.

I just saw there were some changes in that area of code for 0.5: https://github.com/square/SocketRocket/commit/a770a5fd52fd2971275a3391d52fe50cb3a3d0fe

We're still on 0.4.2 though.

**Comment by lvandyk** [comment]
Hi Kommen, it might be the issue. I will test with 0.5

**Comment by lvandyk** [comment]
I realised I was on 0.5.0. Still happens :(

**Comment by kommen** [comment]
@lvandyk does it happen with 0.4.2? Maybe a770a5f which shipped with 0.5 broke it again?

**Comment by lvandyk** [comment]
I think it worked! I'm not getting any silent disconnects anymore! Going to keep testing a bit longer on a device. Thanks alot Kommen!

**Comment by lvandyk** [comment]
Didn't work. Got the silent dc :(

**Comment by kommen** [comment]
@lvandyk I just now saw your edited comment from before: https://github.com/square/SocketRocket/issues/260#issuecomment-206840535 

This sounds like a different issue as we had in #268.

**Comment by nlutsenko** [comment]
Hey guys, I would encourage updating to the latest master and testing whether you can still experience this problem. If yes - please reopen the issue or open the new one and I'll gladly take a deeper look.

**Comment by lvandyk** [comment]
Hi ntlutsenko, the weirdest thing happened. It just stopped silently disconnecting all of a sudden (both on our iOS and Android app). Now it always fires the didDisconnect delegate which is perfect. We didn't change anything on the app or on the server. The mystery continues... but I will report back here if we experience it on the new version. Thanks!

**Comment by nlutsenko** [comment]
Awesome. Glad to hear it. If it resolved by itself, I attribute it to phase of the moon. (More about it here http://www.catb.org/jargon/html/P/-of-the-moon.html). Keep me posted.
