### ISSUE TITLE
0.4 change log?

### ISSUE THREAD

**Issue by lukeredpath** [facebook/SocketRocket#262]
I know I can scan through the commits but would it be possible to get a list of the the changes in 0.4? I've had a request to update libPusher to use this (https://github.com/lukeredpath/libPusher/issues/181) and it would be nice to move to a newer stable release.

**Comment by mikelikespie** [comment]
@lukeredpath We need to start using the milestone feature. I imagine most changes are just compilation fixes. You can look at the change log (worst case) https://github.com/square/SocketRocket/commits/master

**Comment by nlutsenko** [comment]
Looks like that changeling is gone at this point.
I would gladly add it if anyone wants to contribute one.
