### ISSUE TITLE
crash on [SRWebSocket scheduleInRunLoop:forMode:] 

### ISSUE THREAD

**Issue by jinjuezhou** [facebook/SocketRocket#307]
hi,when SRWebSocket connect,my app crash on [SRWebSocket scheduleInRunLoop:forMode:] some time
ps:
before reconnect,old connect has released

0	CoreFoundation	0x0000000186a9749c	__CFStreamScheduleWithRunLoop + 1500
1	XXXXXXXXXX	0x0000000100208820	-[SRWebSocket scheduleInRunLoop:forMode:] + 112
2	XXXXXXXXXX	0x0000000100208770	-[SRWebSocket _connect] + 108
11	XXXXXXXXXX	0x00000001002076f4	-[SRWebSocket open] + 248
12	XXXXXXXXXX	0x00000001001a9760	-[XRWebSocket reconnect] + 624
13	XXXXXXXXXX	0x000000010023d61c	-[TFViewController socketReconnect] + 56
14	libdispatch.dylib	0x000000019895d994	__dispatch_call_block_and_release + 24
15	libdispatch.dylib	0x000000019895d954	__dispatch_client_callout + 16
16	libdispatch.dylib	0x00000001989676f0	__dispatch_after_timer_callback + 92
15	libdispatch.dylib	0x000000019895d954	__dispatch_client_callout + 16
18	libdispatch.dylib	0x0000000198974010	__dispatch_source_latch_and_call + 2052
19	libdispatch.dylib	0x000000019895fabc	__dispatch_source_invoke + 288
20	libdispatch.dylib	0x000000019896a318	__dispatch_root_queue_drain + 720
21	libdispatch.dylib	0x000000019896bc4c	__dispatch_worker_thread3 + 108
22	libsystem_pthread.dylib	0x0000000198b3d22c	_pthread_wqthread + 804
1	libsystem_pthread.dylib	0x0000000198b3cef0	start_wqthread + 4

**Comment by kenwigginton** [comment]
@jinjuezhou I need a full thread dump in order to see where the crash is happening.

If you could also post some clear reproduction steps, I would be happy to try to reproduce.

**Comment by nlutsenko** [comment]
Closing this issue, since it's somewhat stale and doesn't have repro steps.
Please reopen/or open a new issue if you still experience this problem.
