### ISSUE TITLE
Need the ability to override the default origin header

### ISSUE THREAD

**Issue by aprock** [facebook/SocketRocket#321]
When connecting to WebOS devices, such as LG Tv's, SocketRocket's origin string causes the connections to be refused. While the WS spec allows arbitrary strings, this embedded server misbehaves with them.

It would be a ideal if we could override the origin header when needed.

**Comment by aprock** [comment]
here is one solution.
https://github.com/aprock/SocketRocket/commit/de5f7bfcabe000671edc2d7c145222cd44ffeab2

**Comment by nlutsenko** [comment]
Hey @aprock, you actually are able to pass any arbitrary header via SocketRocket by simply adding them to the `NSURLRequest`.

Here is an example:
```objc
NSMutableURLRequest *request = [NSMutableURLRequest requestWithURL:[NSURL URLWithString:@"..."]];
request.allHTTPHeaderFields = @{ @"Origin" : @"%YOUR CUSTOM ORIGIN%" };
SRWebSocket *socket = [[SRWebSocket alloc] initWithURLRequest:request];
[socket open];
...
```

Feel free to reopen/comment/open a new issue if this still doesn't suit you.
