### ISSUE TITLE
[SRWebSocket _initializeStreams] arc leak memory?

### ISSUE THREAD

**Issue by codefei** [facebook/SocketRocket#343]
CFStreamCreatePairWithSocketToHost(NULL, (__bridge CFStringRef)host, port, &readStream, &writeStream);

 NSString -> CFStringRef host cause leak，so whether is need to call CFRelease

**Comment by nlutsenko** [comment]
Hey @codefei,

Doesn't seem like it, taking into account that `__bridge` does not transfer ownership - that string will still be managed by ARC and released automatically. 
For this to be required to be `CFRelease`d - we would have `CFBridgingRetain` or `__bridge_retained`, where it would cast ObjC pointer to CF pointer and transfer an ownership to us.

Let me know if I missed something here (and feel free to reopen this issue).
