### ISSUE TITLE
Consistent 503 error when on Cellular network?

### ISSUE THREAD

**Issue by ghost** [facebook/SocketRocket#35]
My app works great using SocketRocket within the Pusher Framework for Mac.

However, whenever I'm on my Verizon cellular modem, I receive this error (the log is of my own design but the error message comes from - (void)_HTTPHeadersDidFinish; in SRWebSocket

2012-05-13 18:05:23.040 LogMonitor[2704:503] pusher failed to connect Error Domain=org.lolrus.SocketRocket Code=2132 "received bad response code from server 503" UserInfo=0x10181f180 {NSLocalizedDescription=received bad response code from server 503}

Obviously this could be Socket Rocket, it could be Pusher, it could be Verizon, it could be my network, etc.  I'm just hoping that you might have some further insight?  Thanks.

**Comment by gunjotSinghMansa** [comment]
How to change port to 443? Can you please help!

**Comment by gunjotSinghMansa** [comment]
I tried port 443, but didn't help! I am also having connectivity issues over 4g. It works perfect over wifi. I get error "didCloseWithCode --> 1001 and reason ==> Stream end encountered wasClean => 0" .
