### ISSUE TITLE
Assertion failed: (mapped_size >= sizeof(_currentReadMaskOffset) + offset) when call - (void)close;

### ISSUE THREAD

**Issue by dmitriyborodko** [facebook/SocketRocket#355]
When I call [webSocket close] I get crash:
Assertion failed: (mapped_size >= sizeof(_currentReadMaskOffset) + offset), function __33-[SRWebSocket _readFrameContinue]_block_invoke_2, file /PathToProject/Pods/SocketRocket/SocketRocket/SRWebSocket.m, line 1128.

**Comment by nlutsenko** [comment]
Hey @dmitriyborodko, thanks for the report.
Any chance you have a good repro of this crash? I would gladly look into it in that case.
The part that I am specifically interested in:
- Looks like you are getting a masked frame for a huge payload, but the size of the data received doesn't match the data expected + mask key.
- A frame dump that is sent/received by the server that leads to this crash

**Comment by mxbaranov** [comment]
+1 same 
Assertion failed: (mapped_size >= sizeof(_currentReadMaskOffset) + offset), function __33-[SRWebSocket _readFrameContinue]_block_invoke_2, file /ProjectPath/Pods/SocketRocket/SocketRocket/SRWebSocket.m, line 1131.

**Comment by plzen** [comment]
I get this crash when server returns mask bit = 1. In RFC (https://tools.ietf.org/html/rfc6455#section-5.1):

> A server MUST NOT mask any frames that it sends to the client.  A client MUST close a connection if it detects a masked frame.

I think we need to add `return` in if statement here https://github.com/facebook/SocketRocket/blob/0.5.1/SocketRocket/SRWebSocket.m#L1097 to prevent reading payload if server returns mark bit = 1.

**Comment by plzen** [comment]
If it interesting my comment related to this bug in Ratchet websocket server https://github.com/ratchetphp/Ratchet/issues/420, when server returns masked payload

**Comment by nlutsenko** [comment]
@plzen, amazing find! Thank you so much!
Going to mark this as enhancement, and roll out a patch soon, unless someone else wants to give this a go and send a pull request.

**Comment by plzen** [comment]
Hi, @nlutsenko. I created PR #401 with fix.

**Comment by nlutsenko** [comment]
Just merged it in! This is closed now and the fix is going to ship in the next version!
