### ISSUE TITLE
How do I get the information that first handshake returned request header?

### ISSUE THREAD

**Issue by Louis-kin** [facebook/SocketRocket#380]
I need to get for login Authentication - Key after verification.What should I do?

**Comment by nlutsenko** [comment]
Hey @Louis-kin, not sure what you are asking.
Do you want to get the http basic auth response? 
To get the basic auth going - just add an `Authorization` header with an authorization method (in this case `Basic`) and the user name and password of the logged in user in the format `base64(username:password)` (e.g. `Authorization: Basic d2lraHpwQWRpYQ`)

Or are interested in the received http headers in general? We have a property `receivedHTTPHeaders` that should help you going here.

**Comment by Louis-kin** [comment]
Thank you very much! 
Actually, I need the auth-response ,I have to get the Authorization-Key and  handler for encrypting  of it.Then send it to Server.To build the connection.But I do not know how to achieve it with Code。If you can add methods to achieve it in this framework?（ I'm a beginner of iOS-developers)

**Comment by Louis-kin** [comment]
I had sloved the problem with this method:
 NSString *acceptHeader = CFBridgingRelease(CFHTTPMessageCopyHeaderFieldValue( webSocket.receivedHTTPHeaders, CFSTR("Authentication-Key")));
It is hard for me to found this. You can sign the method with /** CFSTR:<#Server response header #> */.
Thanks for your help!
