### ISSUE TITLE
Use of undeclared identifier 'PAGE_SIZE'

### ISSUE THREAD

**Issue by jackielee527** [facebook/SocketRocket#382]
I posted about this issue in previous issue, and am opening with new title to make sure clearly about the issue.

All was working properly on Cocoapods 0.39 before I upgrade to Cocoapods 1.0

After upgrading to Cocoapods 1.0, if I am trying to run on iOS device, I meet following issue in SRWebSocket.h file.

> Use of undeclared identifier 'PAGE_SIZE'

Here is the code block `static const size_t SRDefaultBufferSize = PAGE_SIZE;`

Please let me know if I missed sth with upgrading Cocoapods or this is known issue.

Thanks

**Comment by nlutsenko** [comment]
Not sure why CocoaPods tries to install master by default for you, but I was able to reproduce this issue and am going to fix it soon.
