### ISSUE TITLE
So the project can support IPV6?

### ISSUE THREAD

**Issue by xunlongdingxue** [facebook/SocketRocket#392]
I just start learning iOS，I want to use the project and I have a simple question that is it can support IPV6 of all versions?

**Comment by nlutsenko** [comment]
Yup, absolutely!
We are using CFNetwork and after some testing I did on IPv4+IPv6 network - I was able to make this connect no problem to an IPv6 address.
Please open an issue if you run into any connectivity problems on IPv6 networks.

**Comment by xunlongdingxue** [comment]
Thanks for your reply. When I use iOS 7.1.4  touch and socket open has run, but the delegate -websocketdidopen can not call-back. but iOS9.1 work fine. And should I need use the last version of SRwebSocket?
