### ISSUE TITLE
Socket delegates not called when in custom framework

### ISSUE THREAD

**Issue by lindseyvastola** [facebook/SocketRocket#408]
I took existing working ScoketRocket code put them in a custom framework but the delegate methods aren't being called. I made sure that the delegate was being set and the service was starting.

To start the process from my main project:
let framework = CCCall.SocketSingleton()
  framework.makeTestCall()

Method in framework:
-(void)makeTestCall {
_mSocket = [[SRWebSocket alloc] initWithURLRequest:[NSURLRequest requestWithURL:[NSURL URLWithString:@"wss://websockeURLHere"]]];
        _mSocket.delegate = self;

        [_mSocket open];
}

Delegates not being called:

- (void)webSocketDidOpen:(SRWebSocket *)webSocket;
{
    NSLog(@"Websocket Connected");
}

- (void)webSocket:(SRWebSocket *)webSocket didFailWithError:(NSError *)error;
{
    NSLog(@":( Websocket Failed With Error %@", error);
    _webSocket = nil;
    [self _reconnect];
}

- (void)webSocket:(SRWebSocket *)webSocket didReceiveMessage:(id)message;
{
    NSLog(@"Received \"%@\"", message);
}

- (void)webSocket:(SRWebSocket *)webSocket didCloseWithCode:(NSInteger)code reason:(NSString *)reason wasClean:(BOOL)wasClean;
{
    NSLog(@"WebSocket closed");
    _webSocket = nil;
}

- (void)webSocket:(SRWebSocket *)webSocket didReceivePong:(NSData *)pongPayload;
{
    NSLog(@"Websocket received pong");
}

**Comment by lindseyvastola** [comment]
I found the error. I created the framework in the viewdidload and it stops its value when the method is complete.

**Comment by nlutsenko** [comment]
Glad you found the solution.
Marking this as resolved.
Please reopen or open a new issue if you run into any further problems.
