### ISSUE TITLE
Can this be used to communicate with a SignalR server?

### ISSUE THREAD

**Issue by cincoutprabu** [facebook/SocketRocket#413]
I have a SignalR server running on a given IP:Port, and the URL looks like http://x.x.x.x:8080 instead of typical WebSocket URL that looks like ws://x.x.x.x:8080. Can we use the SocketRocket iOS SDK to communicate with a SignalR server? I'm getting this error while trying to connect to the http SignalR URL: Error Domain=SRWebSocketErrorDomain Code=2132 "received bad response code from server 404".

**Comment by richardgroves** [comment]
Take a look at https://github.com/DyKnow/SignalR-ObjC which uses this library to implement a SignalR client for Objective-C.

**Comment by nlutsenko** [comment]
Looks like that repo indeed does a full implementation of the client. 
Feel free to ping this issue or reopen if you think there is something actionable for us in SocketRocket land.
