### ISSUE TITLE
received bad response code from server 400

### ISSUE THREAD

**Issue by dandawson87** [facebook/SocketRocket#43]
Hey, I hope I am not making myself look too silly, but I get this error when trying to connect to : "ws://echo.websocket.org"

As referenced here:

http://www.websocket.org/echo.html

I am using the testChat example that comes with the tar ball download. And I get the error:

2012-08-06 11:31:24.200 TestChat[6437:707] :( Websocket Failed With Error Error Domain=org.lolrus.SocketRocket Code=2132 "received bad response code from server 400" UserInfo=0x1d9000 {NSLocalizedDescription=received bad response code from server 400}

This is probably my problem and not your's, and I am sorry to post this as an issue but I couldn't find any other way to get some help.

I did some googling, the only explanation i could find was that the version of web sockets that the website is using is different to that of SocketRocket, and the handshake fails. Has anyone else discovered this? 

Any help would be great thanks.

--- EDIT---

It seems that it works perfectly with the test server over port 9000, but for some reason when I send the packet to connect it changes the header values of the handshake from Connection : Upgrade to Connection : Keep Alive

**Comment by chokri** [comment]
I thing it's about to add this on the server side Access-Control-Allow-Origin="*"
