### ISSUE TITLE
Categories for Foundation classes are not linked without -ObjC

### ISSUE THREAD

**Issue by mihui** [facebook/SocketRocket#433]
I upgraded the SocketRocket library recently, it seems the Objective-C category method implementation does not work without adding -ObjC as "Other Linker Flags", and it throws this exception: 

-[NSMutableURLRequest SR_SSLPinnedCertificates]: unrecognized selector sent to instance 0x7fbffc08c990

Is there any alternative way of this category method? Or How could I get rid of this exception without adding any additional flags? 

Thanks.

**Comment by nlutsenko** [comment]
Hey @mihui, thanks for the report.
I am going to poke around at few things to force load the categories, but at this time using `-ObjC` or `-all_load` is required (and was required before we made any changes).

**Comment by mihui** [comment]
Thank you for your support @nlutsenko

**Comment by mihui** [comment]
Wow, that is awesome. Thanks again!!! :+1:
