### ISSUE TITLE
Cocoapods Version not up to date?

### ISSUE THREAD

**Issue by skware** [facebook/SocketRocket#434]
Hi 

when getting Socket Rocket thru cocoa pods , i am getting version 0.5.1 which does not have the same API as the current one from github.

Ex sendData and sendString are not present.

Is the podSpec up to date?

Thanks

**Comment by nlutsenko** [comment]
Hey @skware, yup, the current `master` is very far ahead from the latest public release.
We are still stabilizing and improving on few things in the source, but the release is coming very soon, so stay tuned.

**Comment by skware** [comment]
Ok  great thanks!

**Comment by ljbatwh** [comment]
two years passed, the version in cocoa pod still is 0.5.1?. When the new release will publish?
