### ISSUE TITLE
Clone to my computer,and one error comes:'only factory methods can have the swift name attribute'

### ISSUE THREAD

**Issue by Waitwalker** [facebook/SocketRocket#435]
![1](https://cloud.githubusercontent.com/assets/16695783/16582066/37bb8258-42df-11e6-9f94-88f7c4379fc0.png)

**Comment by nlutsenko** [comment]
@Waitwalker, please make sure you are using latest public version of Xcode (7.3.1) which will automatically resolve this problem.
