### ISSUE TITLE
-[NSURLRequest SR_SSLPinnedCertificates]: unrecognized selector

### ISSUE THREAD

**Issue by fenglinxiu** [facebook/SocketRocket#442]
It has problem when I running my project use libSocketRocket.a.
-[NSURLRequest SR_SSLPinnedCertificates]: unrecognized selector sent to instance 0x155e25bd0

![a745ab04-face-49d9-9cd6-0b2548ec69ee](https://cloud.githubusercontent.com/assets/6799138/16751342/4011be0a-480b-11e6-8f6b-de45383c0425.png)

**Comment by nlutsenko** [comment]
Looks like the same problem as #433 and this should be fixed by either adding `-ObjC` linker flag to your application or by updating to the latest master, which has #441 merged that ultimately fixes the problem for any future release.

**Comment by fenglinxiu** [comment]
thank you. It works.

**Comment by nlutsenko** [comment]
😉
