### ISSUE TITLE
Invalid State: Cannot call send: until connection is open

### ISSUE THREAD

**Issue by alexsanderkhitev** [facebook/SocketRocket#464]
Hello everyone! When I did logout I closed a socket conenction. After I registered a new user and I opened a socketn connection but I got the error "Invalid State: Cannot call send: until connection is open". Why did I receive this error when I check there is a socket connection?   Please help me, how can I fix it?

```
  func setWebSocketConnect() {
        if DBHelper.instance.mainUser != nil {
            if webSocketClient.readyState != .OPEN {
                webSocketClient = SRWebSocket.init(URL: serverURL)
                webSocketClient.delegate = self
                webSocketClient.open()
            }
		} else {
			print("mainUserIsNil")
		}
    }
```

**Comment by raviAggarwal61** [comment]
@alexsanderkhitev Have you found the solution, can you please explain the problem causing scenario?

**Comment by iOSPrincekin** [comment]
I have the same error, how solve it,thanks!
