### ISSUE TITLE
App Store rejection

### ISSUE THREAD

**Issue by simonmaddox** [facebook/SocketRocket#485]
I'm getting the following automated rejection when submitting to the App Store:

> The app references non-public selectors in [MyApp]: _failWithError:, initWithURLRequest:

The only places either of these are used in my app is inside SocketRocket. The only third party dependency my app uses is SocketRocket.

**Comment by simonmaddox** [comment]
Submitted to Apple as rdar://28829166

**Comment by simonmaddox** [comment]
Appears to be fixed now. Stand down 😃

**Comment by erikprice** [comment]
What was the problem?

**Comment by simonmaddox** [comment]
No idea. I resubmitted my app today, and it passed automatic validation. Apple must have changed something on their side.

**Comment by LSsoftware** [comment]
i got the same problem.
