### ISSUE TITLE
SocketRocket.xcodeproj and choose TestChat target  build fail

### ISSUE THREAD

**Issue by ixp9891** [facebook/SocketRocket#488]
SocketRocket.xcodeproj and choose TestChat target  build fail

fail message:
1.cannot create __weak reference in file using manual reference counting
2.'UIKit/Uikt.h' file not found

**Comment by nlutsenko** [comment]
Looks like you didn't clone the submodules when you cloned the repo.
To fix, please run the following in the repo directory after you cloned it:
```
git submodule update --init --recursive
```
