### ISSUE TITLE
SRWebSocketErrorDomain Code=2133

### ISSUE THREAD

**Issue by uujuna** [facebook/SocketRocket#509]
Error Domain=SRWebSocketErrorDomain Code=2133 "Invalid Sec-WebSocket-Accept response." UserInfo={NSLocalizedDescription=Invalid Sec-WebSocket-Accept response.

sr = SRWebSocket(url:URL(string: "ws://hc-link.tpddns.cn:10000")!)
When I switch the port to 10000 It was wrong. If I need to add port，how to init..?

**Comment by uujuna** [comment]
sr = SRWebSocket(url:URL(string: "ws://192.168.199.105:8089")!)
this url can open.
why?

**Comment by uujuna** [comment]
i fix it

**Comment by Said13** [comment]
How did you fix it? @uujuna
