### ISSUE TITLE
Remove assert from send

### ISSUE THREAD

**Issue by mxcl** [facebook/SocketRocket#54]
My program just crashed because the websocket was unexpectedly closed. This is a debug build, but it seems like (as a consumer of your library) I'd rather have the delegate called with an error message, under debug and release mode.

Will provide pull request if you will accept it and tell me what error handling you want instead.

**Comment by cerupcat** [comment]
+1

**Comment by vigneshv59** [comment]
+1

**Comment by dfed** [comment]
@mikelikespie, thoughts on this? I'm a pretty big proponent of not asserting unless the world is on 🔥.
