### ISSUE TITLE
1001,reason:Stream end encountered

### ISSUE THREAD

**Issue by Happylege** [facebook/SocketRocket#541]
When i try to connect my websocket server, I have the problem. Please help me, thank you.

**Comment by zhoupIT** [comment]
@Happylege  hello, how you resolve the problem?

**Comment by Happylege** [comment]
@zhoupIT Can you speak chinese？

**Comment by Happylege** [comment]
@zhoupIT 只要你访问的服务地址没错，端口号没错，所带参数没错，那就应该没问题。我的是因为地址后面要带参数，而我忘记啦！

**Comment by tantan39** [comment]
Translate to english, plz!!!
