### ISSUE TITLE
Error Domain=SRWebSocketErrorDomain Code=2133 "Invalid Sec-WebSocket-Accept response"

### ISSUE THREAD

**Issue by oriben2** [facebook/SocketRocket#66]
The bug that i'm experiencing is very frustrating and help will be very much appreciated.
The deal is this: when using iPhone simulator, request headers (from the server log) are these:
{"host":"hangies.oriben.jit.su:80",
"connection":"Upgrade",
"sec-websocket-version":"13",
"origin":"http://hangies.oriben.jit.su:80/",
"upgrade":"websocket",
"sec-websocket-key":"msASkvBQxS1TvoyPrxF+iw==",
"sec-websocket-protocol":"hangies"}

all is well and connection is established.
BUT! when using a real iphone device:
{ host: 'hangies.oriben.jit.su',
'sec-websocket-key': '42RVDx1k7NUTiQre15hXQw==',
'sec-websocket-version': '13',
origin: 'http://hangies.oriben.jit.su:80/',
'sec-websocket-protocol': 'hangies',
accept: '_/_',
'accept-charset': '*',
via: 'HTTP/1.1 MSP-RH',
'x-forwarded-for': '2.55.118.50',
'x-forwarded-port': '30618',
'x-forwarded-proto': 'http',
connection: 'keep-alive' }

as you can see, upgrade header is missing and connection header is 'keep-alive' instead of 'Upgrade'. this is a "regular" http request and it is being treated like such by my server, which ends up in the websocket failing to connect.

i tried setting the headers manually, like so:

```
NSMutableURLRequest *pushServerRequest = [NSMutableURLRequest requestWithURL:[NSURL URLWithString:hangiesSource]];
[pushServerRequest setValue:@"websocket" forHTTPHeaderField:@"upgrade"];
[pushServerRequest setValue:@"Upgrade" forHTTPHeaderField:@"connection"];
_socketClient = [[SRWebSocket alloc] initWithURLRequest:pushServerRequest protocols:@[@"hangies"]];
```

that didn't help at all. still, "connection":"keep-alive".
does anybody have an idea?

**Comment by gunjotSinghMansa** [comment]
How to change port to 443? Can you please help!

**Comment by gunjotSinghMansa** [comment]
I tried port 443, but didn't help! I am also having connectivity issues over 4g. It works perfect over wifi.  I get error "didCloseWithCode --> 1001 and reason ==> Stream end encountered wasClean => 0" .

**Comment by Ashish11111** [comment]
i also got this error
didFailWithError: Optional(Error Domain=SRWebSocketErrorDomain Code=2133 "Invalid Sec-WebSocket-Accept response" UserInfo={NSLocalizedDescription=Invalid Sec-WebSocket-Accept response})
Error : Optional("Invalid Sec-WebSocket-Accept response")

**Comment by mohanrajmca** [comment]
didFailWithError: Optional(Error Domain=SRWebSocketErrorDomain Code=2133 "Invalid Sec-WebSocket-Accept response" UserInfo={NSLocalizedDescription=Invalid Sec-WebSocket-Accept response})
