### ISSUE TITLE
Dangling delegate pointer results in crashes

### ISSUE THREAD

**Issue by mattmassicotte** [facebook/SocketRocket#78]
I've been trying to track down an intermittent crash in SocketRocket.  It always ends up happening in the same place - the block in -[SRWebSocket _handleMessage].  Here's what I think is happening:
- the block in _handleMessage is constructed and submitted to _delegateDispatchQueue, resulting in retaining self and the queue itself
- My object (the SRWebSocket's delegate) gets deallocated
- It releases SRWebSocket, but because of [self retain] in _handleMessage, the SRWebSocket instance is not deallocated
- the block then runs, but uses self's delegate pointer, which is now dangling

Calling setDelegate:nil makes this a much less-likely race to hit, but it is still possible because because of the lack of synchronization between the delegate ivar and the blocks submitted to _delegateDispatchQueue.

There are a few things I can think of that might address this.  Here's one:
- (void)setDelegate:(id <SRWebSocketDelegate>)delegate
  {
  [self _performDelegateBlock:^{
      _delegate = delegate;
  }];
  }

Because changes to the _delegate variable can happen on any queue, but access seems to only happen on _delegateDispatchQueue, I believe this is the safest change.  If you guys concur, I can put together a PR.

**Comment by MudassirAsghar22** [comment]
app crashes on every time  - (void)_handleMessage:(id)message giving the error webSocket:didReceiveMessage:]: unrecognized selector sent to instance 0x105dea940'
