### ISSUE TITLE
Stream end encountered

### ISSUE THREAD

**Issue by tawnkramer** [facebook/SocketRocket#82]
I'm able to start a connection to my server. But very shortly thereafter the connection closes with the error:

"Stream end encountered"

where wasClean is false.
This is iOS 6.1 with a recent pull of SocketRocket from github. My backend is Nodejs v0.8.19.

I'm able to connect to the same server with socket.io javascript from a browser. Does anyone know what the problem might be?

**Comment by pingzhusong** [comment]
@tawnkramer So how did you solved this issue?, I also get this issue for wss://blabal.bla/

**Comment by qbshen** [comment]
when connect Socket.io  , you should append "/socket.io/?EIO=4&transport=websocket", good luck!

**Comment by ShengkunZhang** [comment]
@qbshen thanks
