### ISSUE TITLE
VOIP and background sockets

### ISSUE THREAD

**Issue by robreuss** [facebook/SocketRocket#95]
A common use case for WebSockets is to enable a VOIP app to receive call notifications while in the background.

The issues involved in keeping a socket alive in the background for a VOIP app are discussed in the programming guide on page 121: 

http://developer.apple.com/library/ios/documentation/iphone/conceptual/iphoneosprogrammingguide/iphoneappprogrammingguide.pdf

It seems like SocketRocket uses NSStream, so supporting this functionality would involve optionally setting a property on the stream where NSStreamNetworkServiceType is set to NSStreamNetworkServiceTypeVoIP.

Any thought to adding this as a configuration option?

FYI, my specific requirement is to support this through libPusher, which would in the best case leverage that parameter to expose it's own version:

https://github.com/lukeredpath/libPusher/issues/96

**Comment by lylepratt** [comment]
We are experiencing this deficiency now as well. Is there a good reason the PR has not been accepted?

**Comment by mikelikespie** [comment]
can the PR be reopened? Also need CLA to be signed.

**Comment by MihaMajcen** [comment]
I think that correct way for implementing this feature is to set networkServiceType in NSURLRequest which is passed into init function. This way we can support multiple serviceTypes not just voip. 

I've implemented it in #312

**Comment by nlutsenko** [comment]
Closing as it is indeed fully implemented via `NSURLRequest` `networkServiceType` property and is available in the latest release.
